Repository relax-together/relax-together-backend, pull requests merged in 2024-10, with the labels that each got.

#107 fix: cors 문제로 origin 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
Labels: 🐞 BugFix

#109 [#108] 토큰 발급 방식 수정
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/user/response/JwtResponse.java
Labels: 🔨 Refactor

#111 [#110] 토큰 재발급 API URI 수정 및 스웨거 관련 어노테이션 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
Labels: 🔨 Refactor

#113 [#112] LocalDatetime -> ZonedDateTime 변경
  src/main/java/kr/codeit/relaxtogether/config/JacksonConfig.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/request/CreateGatheringRequest.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/request/GatheringSearchCondition.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/GatheringDetailResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/HostedGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/MyGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/Participant.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/ParticipantsResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/SearchGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/review/request/ReviewSearchCondition.java
  src/main/java/kr/codeit/relaxtogether/dto/review/response/ReviewDetailsResponse.java
  src/main/java/kr/codeit/relaxtogether/entity/BaseTimeEntity.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Gathering.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Location.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Type.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/dto/gathering/CreateGatheringRequestTest.java
  src/test/java/kr/codeit/relaxtogether/entity/gathering/GatheringTest.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🔨 Refactor

#115 [#114] 개발용 모임 데이터 날리기 api
  src/main/java/kr/codeit/relaxtogether/controller/AdminController.java
Labels: 💪🏻 Feature

#117 [#116] 로그인 유저 정보 조회 데이터에 id 추가
  src/main/java/kr/codeit/relaxtogether/dto/user/response/UserDetailsResponse.java
Labels: 🔨 Refactor

#119 [#118] 쿠키에 로그인 사용자 판별 정보를 추가
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
Labels: 🔨 Refactor

#122 [#121] 토큰 유효시간 변경
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
Labels: ⚙ Setting

#124 [#123] 토큰 유효시간 변경(1분, 5분)
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
Labels: ⚙ Setting

#126 [#125] 모임 조회 시 만료된 모임은 아래로 보내도록 변경
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/SearchGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🔨 Refactor

#129 [#128] 인증이 필요하지 않은 API 요청에 대한 토큰 처리 로직 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
Labels: 🐞 BugFix

#130 [#127] 모임 조회 시 마감된 모임은 뒤로 가도록 수정
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🐞 BugFix

#132 [#131] TimeZone UTC로 변경
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
Labels: 🔨 Refactor

#134 [#133] 잘못된 인증 인가 로직 수정 및 쿼리 파라미터 빈 문자열 처리 로직 추가
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
Labels: 🐞 BugFix

#136 [#135] 테스트를 위한 토큰 유효 시간 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
Labels: ⚙ Setting

#138 [#137] jwtFilter uri 정규표현식 추가
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
Labels: 🐞 BugFix

#140 [#139] 모임생성 이미지 URL 예시 수정
  src/main/java/kr/codeit/relaxtogether/dto/gathering/request/CreateGatheringRequest.java
Labels: 📜 Docs

#142 [#141] typeDetail require = false
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
Labels: 🐞 BugFix, 🔨 Refactor

#145 [#144 userId를 반환하도록 변경
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/Participant.java
Labels: 🐞 BugFix

#146 [#143] 토큰 관련 API 에러 메시지 수정 및 리뷰 조회 쿼리파람인 typeDetail 삭제
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/request/ReviewSearchCondition.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 🔨 Refactor

#148 [#147] 토큰 만료 메시지 적용대상 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
Labels: 🔨 Refactor

#150 [#149] 토큰 재발급 요청 시, refresh 토큰이 만료된 상태라면 로그아웃과 동일하게 처리하도록 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
Labels: 🔨 Refactor

#152 [#151] 리뷰 조회 결과에 누락된 데이터(모임 이미지) 추가
  src/main/java/kr/codeit/relaxtogether/dto/review/request/WriteReviewRequest.java
  src/main/java/kr/codeit/relaxtogether/dto/review/response/ReviewDetailsResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
Labels: 🔨 Refactor

#154 [#153] 토큰 유효 시간 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
Labels: 🔨 Refactor

#157 [#156] 유저 모임 목록 조회 인증없이 통과하도록 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
Labels: 🔨 Refactor

#159 [#158] type 파라미터 버그 수정
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
Labels: 🐞 BugFix

#160 [#155] 이메일을 통한 인증 로직 추가 및 비밀번호 변경 API 구현
  build.gradle
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/EmailController.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/email/request/SendEmailRequest.java
  src/main/java/kr/codeit/relaxtogether/dto/email/request/TokenVerificationRequest.java
  src/main/java/kr/codeit/relaxtogether/dto/email/response/TokenVerificationResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/user/request/ChangePasswordRequest.java
  src/main/java/kr/codeit/relaxtogether/entity/User.java
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
  src/main/java/kr/codeit/relaxtogether/service/EmailService.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/main/resources/static/images/logo-icon.png
  src/main/resources/static/images/logo-text.png
  src/main/resources/templates/email.html
  src/test/resources/application.yml
Labels: 💪🏻 Feature

#162 [#161] 잘못된 인증 설정 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
Labels: 🐞 BugFix

#164 [#163] 응답 DTO에 누락된 어노테이션 추가
  src/main/java/kr/codeit/relaxtogether/dto/email/response/TokenVerificationResponse.java
Labels: 🐞 BugFix

#166 [#165] 회원가입에 이메일 인증 과정 추가
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/EmailController.java
  src/main/java/kr/codeit/relaxtogether/dto/email/request/CodeVerificationRequest.java
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
  src/main/java/kr/codeit/relaxtogether/service/EmailService.java
  src/main/resources/templates/email-password-change.html
  src/main/resources/templates/email-signup.html
Labels: 💪🏻 Feature

#168 [#167] 회원가입을 위한 메일 인증 과정에서 잘못된 검증 로직 수정
  src/main/java/kr/codeit/relaxtogether/service/EmailService.java
Labels: 🐞 BugFix

#170 [#169] 테스트를 위해 토큰 유효시간 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
Labels: ⚙ Setting

#171 [#171] accessToken 유효시간을 60분으로 수정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
Labels: ⚙ Setting

#173 [#172] 로그 설정
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/config/QuerydslConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/exception/security/CustomAuthenticationEntryPoint.java
Labels: 🔨 Refactor
