Repository relax-together/relax-together-backend, pull requests merged in 2024-09, with the labels that each got.

#2 env: jacocoTest 제외 범위 수정
  build.gradle
Labels: ⚙ Setting

#6 [#3] SwaggerConfig 추가
  .github/workflows/build.yml
  build.gradle
  src/main/java/kr/codeit/relaxtogether/config/SwaggerConfig.java
Labels: ⚙ Setting

#5 [#4] 엔터티 클래스 연관관계 매핑
  src/main/java/kr/codeit/relaxtogether/RelaxtogetherApplication.java
  src/main/java/kr/codeit/relaxtogether/entity/BaseTimeEntity.java
  src/main/java/kr/codeit/relaxtogether/entity/Gathering.java
  src/main/java/kr/codeit/relaxtogether/entity/Review.java
  src/main/java/kr/codeit/relaxtogether/entity/User.java
  src/main/java/kr/codeit/relaxtogether/entity/UserGathering.java
  src/main/java/kr/codeit/relaxtogether/repository/GatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/ReviewRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/UserRepository.java
Labels: 💪🏻 Feature

#9 [#7] 이메일 중복 검증 API 구현
  build.gradle
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/user/request/EmailCheckRequest.java
  src/main/java/kr/codeit/relaxtogether/repository/UserRepository.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/test/java/kr/codeit/relaxtogether/repository/UserRepositoryTest.java
  src/test/java/kr/codeit/relaxtogether/service/UserServiceTest.java
Labels: 💪🏻 Feature

#11 [#10] 회원가입 API 구현
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/user/request/JoinUserRequest.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/test/java/kr/codeit/relaxtogether/repository/UserRepositoryTest.java
  src/test/java/kr/codeit/relaxtogether/service/UserServiceTest.java
Labels: 💪🏻 Feature

#14 [#12] 회원 수정 API 구현
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/user/request/UpdateUserRequest.java
  src/main/java/kr/codeit/relaxtogether/entity/User.java
  src/main/java/kr/codeit/relaxtogether/repository/UserRepository.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/test/java/kr/codeit/relaxtogether/entity/UserTest.java
  src/test/java/kr/codeit/relaxtogether/repository/UserRepositoryTest.java
  src/test/java/kr/codeit/relaxtogether/service/UserServiceTest.java
Labels: 💪🏻 Feature

#13 [#10] 모임 추가 기능 구현
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/CreateGatheringRequest.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Gathering.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Location.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Type.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/UserGathering.java
  src/main/java/kr/codeit/relaxtogether/repository/GatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/dto/gathering/CreateGatheringRequestTest.java
  src/test/java/kr/codeit/relaxtogether/entity/gathering/GatheringTest.java
Labels: 💪🏻 Feature

#21 [#20] 회원 정보 조회 API 구현
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/user/response/UserDetailsResponse.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/test/java/kr/codeit/relaxtogether/service/UserServiceTest.java
Labels: 💪🏻 Feature

#23 [#22] 모임 생성 api 리팩터링
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/request/CreateGatheringRequest.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🔨 Refactor

#25 [#24] User 엔터티 및 관련 API URI 수정
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/entity/User.java
Labels: 🔨 Refactor

#27 [#26] 모임 목록조회 리팩터링
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Gathering.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Status.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
Labels: 🔨 Refactor

#30 [#29] 모임 상세 api 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/GatheringDetailResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 💪🏻 Feature

#32 [#31] 모임 참여 기능 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 💪🏻 Feature

#34 [#33] 로그인 로직 수정
  src/main/java/kr/codeit/relaxtogether/auth/LoginFilter.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/user/request/LoginRequest.java
Labels: 🔨 Refactor

#37 [#36] 모임 취소 기능 추가
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/request/CreateGatheringRequest.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/request/GatheringSearchCondition.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/GatheringDetailResponse.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/SearchGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Gathering.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 💪🏻 Feature

#38 [#35] 모임 참여 취소 기능 구현
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 💪🏻 Feature

#40 refactor: http 메소드 put -> delete 변경
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
Labels: 🐞 BugFix

#42 [#41] 특정 모임 참가자 목록 조회 기능 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/Participant.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/ParticipantsResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 💪🏻 Feature

#44 [#43] 특정 모임 참가자 목록 조회 시 페이지 정보 반환하도록 리팩토링
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/ParticipantsResponse.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🔨 Refactor

#47 [#46] 내가 만든 모임 조회 기능 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/HostedGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 💪🏻 Feature

#49 [#46] Swagger API 문서가 명확하도록 Pageable 파라미터 수정
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
Labels: 🔨 Refactor

#51 [#50] Swagger 문서 최신화
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
Labels: 🔨 Refactor

#53 [#52] Swagger https
  src/main/java/kr/codeit/relaxtogether/config/SwaggerConfig.java
Labels: ⚙ Setting

#54 [#45] 리뷰 작성 API 구현
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/request/WriteReviewRequest.java
  src/main/java/kr/codeit/relaxtogether/entity/Review.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/service/ReviewServiceTest.java
Labels: 💪🏻 Feature

#58 [#57] 예외처리 리팩터링
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/exception/ApiException.java
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
  src/main/java/kr/codeit/relaxtogether/exception/ErrorResponse.java
  src/main/java/kr/codeit/relaxtogether/exception/GlobalExceptionHandler.java
  src/main/java/kr/codeit/relaxtogether/exception/security/CustomAccessDeniedHandler.java
  src/main/java/kr/codeit/relaxtogether/exception/security/CustomAuthenticationEntryPoint.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🔨 Refactor

#61 [#60] 내가 참석한 모임 필터 추가
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
Labels: 🐞 BugFix

#62 [#56] 로그인 사용자의 리뷰 목록 조회 API 구현
  src/main/java/kr/codeit/relaxtogether/auth/jwt/QuerydslConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/response/ReviewDetailsResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/ReviewRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/gathering/GatheringRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepository.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 💪🏻 Feature

#69 [#68] 주최자가 모임 참여 취소 할 수 없도록 리팩터링
  src/main/java/kr/codeit/relaxtogether/entity/gathering/Gathering.java
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
Labels: 🔨 Refactor

#70 [#65] 해당 모임의 리뷰 목록 조회 기능 API 구현
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 💪🏻 Feature

#73 [#72] 주최자 관련 테스트 코드 수정
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🐞 BugFix

#74 [#71] 로그인 사용자의 리뷰 목록 조회 API에 무한 스크롤을 위한 설정 추가
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/response/ReviewDetailsResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
  src/test/java/kr/codeit/relaxtogether/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#76 [#75] 이메일 중복 검증 관련 에러 응답 추가
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/test/java/kr/codeit/relaxtogether/service/UserServiceTest.java
Labels: 🔨 Refactor

#81 [#80] 페이지네이션 처리를 위해 모임 리뷰 목록 조회 응답 스펙 수정
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/response/GatheringReviewsResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 🔨 Refactor

#83 [#82] 유저의 기본 프로필 이미지 설정
  src/main/java/kr/codeit/relaxtogether/dto/user/request/JoinUserRequest.java
  src/main/java/kr/codeit/relaxtogether/entity/User.java
Labels: 🔨 Refactor

#86 [#85] 나의 모임 조회 리팩터링
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/dto/gathering/response/MyGatheringResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepository.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
  src/test/java/kr/codeit/relaxtogether/service/GatheringServiceTest.java
Labels: 🔨 Refactor

#88 [#87] Pagenation 수정 및 나의 모임 조회 수정
  src/main/java/kr/codeit/relaxtogether/controller/GatheringController.java
  src/main/java/kr/codeit/relaxtogether/repository/UserGatheringRepository.java
  src/main/java/kr/codeit/relaxtogether/service/GatheringService.java
Labels: 🔨 Refactor

#89 [#77] 필터링, 정렬 기준에 따른 리뷰 조회 API 구현
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/request/ReviewSearchCondition.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 💪🏻 Feature

#91 [#90] 스웨거에서 보여주기 위해 어노테이션 추가
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/request/ReviewSearchCondition.java
Labels: 🔨 Refactor

#94 [#93] 필터링한 리뷰들의 평점별 개수를 얻는 API 구현
  src/main/java/kr/codeit/relaxtogether/controller/ReviewController.java
  src/main/java/kr/codeit/relaxtogether/dto/review/response/ReviewScoreCountResponse.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustom.java
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 💪🏻 Feature

#97 [#96] 조건에 따라 정렬할 때, 동일한 조건이 있는 경우에는 리뷰를 최신순으로 정렬하도록 수정
  src/main/java/kr/codeit/relaxtogether/repository/review/ReviewRepositoryCustomImpl.java
  src/test/java/kr/codeit/relaxtogether/repository/ReviewRepositoryTest.java
Labels: 🔨 Refactor

#99 [#98] 누락된 예외 처리 추가
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
  src/main/java/kr/codeit/relaxtogether/service/ReviewService.java
  src/main/java/kr/codeit/relaxtogether/service/UserService.java
  src/test/java/kr/codeit/relaxtogether/service/ReviewServiceTest.java
Labels: 🔨 Refactor

#101 [#100] Refresh Token의 추가와 토큰 재발급 API 구현
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtFilter.java
  src/main/java/kr/codeit/relaxtogether/auth/jwt/JwtUtil.java
  src/main/java/kr/codeit/relaxtogether/config/SecurityConfig.java
  src/main/java/kr/codeit/relaxtogether/controller/UserController.java
  src/main/java/kr/codeit/relaxtogether/exception/ErrorCode.java
Labels: 💪🏻 Feature

#103 [#102] CI/CD 스크립트 작성
  .github/workflows/deploy.yml
Labels: ⚙ Setting

#105 [#104] Deploy 스크립트 오타 정정
  .github/workflows/deploy.yml
Labels: 🐞 BugFix
